language: node_js

node_js:
- node
- 'lts/*'

cache: npm

before_script:
    - npm install
script:
    - node index.js

deploy:
    provider: releases
    api_key: "GITHUB_OAUTH_TOKEN"
    file_glob: true
    file: indices/*
    skip_cleanup: true