language: node_js

node_js:
- node
- 'lts/*'

cache: npm

before_script:
    - npm install
script:
    - node index.js

deploy:
    provider: pages
    github_token: $TRAVIS_GITHUB_TOKEN
    target_branch: master
    # file_glob: true
    # file: indices/*
    cleanup: true
    edge: true
    on:
        branch: master