language: node_js

node_js:
- node
- 'lts/*'

cache: npm

before_script:
    - npm install
script:
    - node index.js

deploy:
    provider: pages
    api_key: $TRAVIS_GITHUB_TOKEN
    file_glob: true
    file: indices/*
    cleanup: true
    on:
        branch: master