name: NPM CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create search indices
      - run: npm install
      - run: node index.js
      - name: Commit files
      - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --local user.name "github-actions[bot]"
      - run: git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
